# yaml-language-server: $schema=https://raw.githubusercontent.com/Vivswan/repo-settings-as-code/main/lib/settings.schema.json

#
# GitHub repository configuration-as-code, applied to GitHub by the
# "Apply Settings" workflow.
#
# Explicit ownership of this file MUST be defined in `CODEOWNERS`. Otherwise,
# anyone who can push changes to this file to the default branch have admin
# control over the repository's settings (the apply-settings workflow runs
# under an admin-scoped token). Users don't need admin privileges themselves
# to trigger this workflow. The solution is to lock down who can commit/approve
# changes to this file on the main trunk.
#
# https://github.com/Vivswan/repo-settings-as-code
#

repository:

  # The name of the repository. ⚠️ Changing this will rename the repository,
  # and thereby change its URL.
  name: template

  # A short description of the repository that will show up in the GitHub UI.
  description: A template for new code repositories.

  # A URL with more information about the project.
  homepage: ''

  # A comma-separated list of topics.
  topics: []

  # Is this a private repository?
  private: false

  # Enable issues?
  has_issues: true

  # Enable projects?
  has_projects: false

  # Enable a wiki for this repo?
  has_wiki: false

  # Enable downloads?
  has_downloads: false

  # The default branch.
  default_branch: latest/dev

  # Allow PRs to be squash-merged.
  allow_squash_merge: true

  # Allow PRs to be resolved with explicit merge commits.
  allow_merge_commit: false

  # Allow PRs to be resolved using the rebase strategy.
  allow_rebase_merge: true

  # Automatically delete source branches when a PR is merged?
  delete_branch_on_merge: true

  # Enable automated security fixes?
  enable_automated_security_fixes: true

  # Enable vulnerability alerts?
  enable_vulnerability_alerts: true

# Define labels for issues and PRs.
# This is handled separately by the "Push Labels" / "Sync Labels" workflows,
# which effectively allow labels to be defined once in a single repository and
# from there synced with multiple other repositories.

#labels:
#  - name: 'Label Name'
#    color: FFFFFF

# Configure branch protection rules.
branches:
  - name: latest/dev
    protection: null
